name: healthprime
description: Health & Fitness Tracking App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.18.0
  percent_indicator: ^4.0.0
  font_awesome_flutter: ^10.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.0
  firebase_database: ^11.0.0
  workmanager: ^0.6.0
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.4.0
  connectivity_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/